import type { Component } from 'vue';
import {
  Archive,
  ArchiveRestore,
  ArrowUp,
  BrainCircuit,
  Building2,
  Briefcase,
  Check,
  ChevronRight,
  Clock,
  Copy,
  FileText,
  Focus,
  Folder,
  History,
  Inbox,
  Info,
  LifeBuoy,
  Lightbulb,
  Lock,
  Menu,
  MessageCircle,
  Mic,
  MicOff,
  Play,
  Square,
  Monitor,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRight,
  PanelRightClose,
  PanelRightOpen,
  Phone,
  Pin,
  PinOff,
  PhoneOff,
  Paperclip,
  Pencil,
  Plus,
  RotateCcw,
  Route,
  Search,
  Send,
  Server,
  Settings,
  ShieldCheck,
  SquareTerminal,
  Sun,
  Trash2,
  TriangleAlert,
  X,
} from 'lucide-vue-next';

/**
 * The only place that knows where the icons come from (D-061): today
 * lucide-vue-next. Components use `<Icon name="…">` with these names; to
 * switch to our own SVGs or another library, change this file only.
 */
export const ICONS = {
  chat: MessageCircle,
  new: Plus,
  send: ArrowUp,
  rename: Pencil,
  archive: Archive,
  restore: ArchiveRestore,
  delete: Trash2,
  expand: ChevronRight,
  close: X,
  menu: Menu,
  panel: PanelRight,
  'sidebar-collapse': PanelLeftClose,
  'sidebar-expand': PanelLeftOpen,
  'panel-collapse': PanelRightClose,
  'panel-expand': PanelRightOpen,
  'theme-light': Sun,
  'theme-dark': Moon,
  'theme-system': Monitor,
  approve: Check,
  saved: Check,
  warning: TriangleAlert,
  project: Folder,
  private: Lock,
  work: Briefcase,
  coder: SquareTerminal,
  telegram: Send,
  router: Route,
  gateway: ShieldCheck,
  system: LifeBuoy,
  retry: RotateCcw,
  attach: Paperclip,
  mic: Mic,
  'mic-off': MicOff,
  play: Play,
  stop: Square,
  phone: Phone,
  'phone-off': PhoneOff,
  clock: Clock,
  settings: Settings,
  info: Info,
  server: Server,
  file: FileText,
  history: History,
  copy: Copy,
  inbox: Inbox,
  knowledge: BrainCircuit,
  office: Building2,
  thoughts: Lightbulb,
  search: Search,
  focus: Focus,
  pin: Pin,
  unpin: PinOff,
} satisfies Record<string, Component>;

export type IconName = keyof typeof ICONS;
